services:
  database:
    image: pgvector/pgvector:pg15
    restart: always
    volumes:
      - db_data1:/var/lib/postgresql/data
      - ./init_database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_DB=${DBNAME}
    ports:
      - 5434:5432

  redis:
    image: redis
    restart: always
    ports:
      - 5433:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  minio:
    image: minio/minio
    restart: always
    container_name: local-minio
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
       - MINIO_ROOT_USER=${MINIO_ROOT_USER}
       - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

volumes:
  db_data1:
  redis_data:
  minio_data:
