# fly.toml app configuration file generated for ridwanbackend-holy-shape-1365 on 2025-10-13T15:56:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ridwanbackend-holy-shape-1365'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
