# fly.toml app configuration file generated for pdfverse-backend on 2026-06-21T13:45:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pdfverse-backend'
primary_region = 'ams'

[build]

[env]
  APP_URL = 'https://flutter.shevyverse.com'
  MAIL_ADDRESS = 'shevyverse@gmail.com'
  OPENAI_EMBEDDING_URL = 'https://api.openai.com/v1/embeddings'
  OPENAI_MESSAGING_URL = 'https://api.openai.com/v1/chat/completions'
  OPENAI_MODEL = 'text-embedding-3-small'
  OPENAI_RESPONSE_MODEL = 'gpt-4.1-mini'
  REDIRECT_URL = 'https://api.shevyverse.com'
  SMTP_URL = 'smtp.gmail.com'
  STORAGE_PROVIDER = 'supabase'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
