//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub chat_info_id: Uuid,
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub timestamp: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_info::Entity",
        from = "Column::ChatInfoId",
        to = "super::chat_info::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChatInfo,
}

impl Related<super::chat_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
