//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "document_chunk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub chat_id: Uuid,
    pub chunk_index: i32,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "custom(\"vector\")", nullable, select_as = "FLOAT4[]")]
    pub embedding: Option<Vec<f32>>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chat_info::Entity",
        from = "Column::ChatId",
        to = "super::chat_info::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChatInfo,
}

impl Related<super::chat_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
