//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    #[sea_orm(column_type = "custom(\"citext\")", nullable, unique)]
    pub email: Option<String>,
    pub password: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub email_verified: bool,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_info::Entity")]
    ChatInfo,
    #[sea_orm(has_many = "super::providers::Entity")]
    Providers,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
}

impl Related<super::chat_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatInfo.def()
    }
}

impl Related<super::providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Providers.def()
    }
}

impl Related<super::tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
